export enum Mood {
  INDICATIVO = "INDICATIVO",
  SUBJUNTIVO = "SUBJUNTIVO",
  IMPERATIVO = "IMPERATIVO",
}

export enum Tense {
  PRESENTE                   = "PRESENTE",
  PRETERITO_INDEFINIDO       = "PRETERITO_INDEFINIDO",
  PRETERITO_IMPERFECTO       = "PRETERITO_IMPERFECTO",
  PRETERITO_PERFECTO_COMPUESTO = "PRETERITO_PERFECTO_COMPUESTO",
  PRETERITO_PLUSCUAMPERFECTO = "PRETERITO_PLUSCUAMPERFECTO",
  FUTURO_SIMPLE              = "FUTURO_SIMPLE",
  FUTURO_PERFECTO            = "FUTURO_PERFECTO",
  CONDICIONAL_SIMPLE         = "CONDICIONAL_SIMPLE",
  CONDICIONAL_PERFECTO       = "CONDICIONAL_PERFECTO",
  IMPERFECTO_RA              = "IMPERFECTO_RA",
  IMPERFECTO_SE              = "IMPERFECTO_SE",
  IMPERATIVO_AFIRMATIVO      = "IMPERATIVO_AFIRMATIVO",
  IMPERATIVO_NEGATIVO        = "IMPERATIVO_NEGATIVO",
}

export enum Person {
  YO                   = "YO",
  TU                   = "TU",
  EL_ELLA_USTED        = "EL_ELLA_USTED",
  NOSOTROS             = "NOSOTROS",
  VOSOTROS             = "VOSOTROS",
  ELLOS_ELLAS_USTEDES  = "ELLOS_ELLAS_USTEDES",
}

export type Language = "de" | "en"
